export const products = [
  [
    "anel-bali",
    "Anel Bali",
    "Anéis",
    "1752534044231-anel2.jpg",
    "Texturas que contam histórias. Um desenho orgânico para acompanhar todos os seus dias.",
  ],
  [
    "colar-coracao",
    "Colar Coração",
    "Colares",
    "1752725398541-correntecoracao.webp",
    "Pequenos corações, grandes significados. Delicadeza em cada elo.",
  ],
  [
    "pulseira-coracao",
    "Pulseira Corações",
    "Pulseiras",
    "1752763404786-PulseiraCoracao.webp",
    "Um encontro entre movimento, leveza e afeto.",
  ],
  [
    "brinco-bali",
    "Brincos Coração Bali",
    "Brincos",
    "1752763360437-Brincobali.webp",
    "O romantismo do coração com a personalidade dos detalhes Bali.",
  ],
  [
    "anel-coracao",
    "Anel Coração",
    "Anéis",
    "1752818004204-Anelcoracao.webp",
    "Um detalhe especial para fazer parte da sua história.",
  ],
  [
    "colar-veneziana",
    "Corrente Veneziana",
    "Colares",
    "1752723734514-Correnteveneziana.webp",
    "Um clássico sutil para usar sozinho ou criar suas próprias combinações.",
  ],
  [
    "pulseira-bali",
    "Pulseira Bali",
    "Pulseiras",
    "1752763311637-Pulseirabali.webp",
    "Textura e personalidade em um desenho atemporal.",
  ],
  [
    "pingo-luz",
    "Brincos Pingo de Luz",
    "Brincos",
    "1752814420970-PingodeLuz.webp",
    "Um ponto de luz. Infinitas possibilidades.",
  ],
  [
    "berloque-coracao",
    "Berloque Coração",
    "Berloques",
    "1752814668635-BerloqueCoracao.webp",
    "Guarde o que faz seu coração sorrir.",
  ],
  [
    "relicario",
    "Relicário do Amor",
    "Pingentes",
    "1752763135509-Relicario.webp",
    "Para levar suas memórias favoritas sempre por perto.",
  ],
  [
    "pena",
    "Pingente Pena",
    "Pingentes",
    "1752763227126-Pingentedepena.webp",
    "A liberdade de ser você em um detalhe delicado.",
  ],
  [
    "ancora",
    "Berloque Âncora",
    "Berloques",
    "1752762796636-BerloqueAncora.webp",
    "Um símbolo de tudo aquilo que nos mantém perto.",
  ],
  [
    "cartier",
    "Corrente Cartier",
    "Colares",
    "1752726543655-Correntecartier.webp",
    "Elos marcantes para composições cheias de personalidade.",
  ],
  [
    "bolinhas",
    "Corrente de Bolinhas",
    "Colares",
    "1752723571701-Correntedebolinha.webp",
    "Um ritmo delicado de pequenos detalhes.",
  ],
  [
    "baleia",
    "Colar Rabo de Baleia",
    "Colares",
    "1752726623289-colarrabodebaleia.webp",
    "Um convite a levar um pouco do mar com você.",
  ],
  [
    "porta-joias",
    "Porta-joias",
    "Acessórios",
    "1752785077773-Portajoias.webp",
    "Um lugar especial para guardar suas peças favoritas.",
  ],
].map(([id, name, category, image, description]) => ({
  id,
  name,
  category,
  image: `/${image}`,
  description,
}));
export const categories = ["Todas", ...new Set(products.map((p) => p.category))];
